import {
  FaAws, FaBootstrap, FaBolt, FaChartBar, FaChartLine, FaCode, FaCss3Alt, FaDatabase,
  FaDocker, FaEye, FaFileExcel, FaFilePdf, FaGithub, FaGitAlt, FaHtml5, FaJava,
  FaLayerGroup, FaLinux, FaMemory, FaNodeJs, FaPlug, FaPython, FaReact, FaRobot,
  FaVideo, FaVolumeUp, FaVuejs,
} from "react-icons/fa";
import {
  SiDuckdb, SiExpress, SiFastapi, SiFirebase, SiFlask, SiIonic, SiJavascript, SiJupyter, SiMongodb,
  SiMysql, SiNetlify, SiNextdotjs, SiNumpy, SiOpencv, SiPandas, SiPostgresql,
  SiRailway, SiSpringboot, SiSupabase, SiTailwindcss, SiTensorflow, SiTypescript,
  SiVim, SiVite,
} from "react-icons/si";

const MAP: Record<string, { Icon: React.ComponentType<{ size?: number | string; style?: React.CSSProperties; className?: string }>; color: string }> = {
  "Python": { Icon: FaPython, color: "#3776AB" },
  "JavaScript": { Icon: SiJavascript, color: "#F7DF1E" },
  "TypeScript": { Icon: SiTypescript, color: "#3178C6" },
  "Java": { Icon: FaJava, color: "#ED8B00" },
  "HTML": { Icon: FaHtml5, color: "#E34F26" },
  "CSS": { Icon: FaCss3Alt, color: "#1572B6" },
  "React": { Icon: FaReact, color: "#61DAFB" },
  "React 19": { Icon: FaReact, color: "#61DAFB" },
  "Vue.js": { Icon: FaVuejs, color: "#4FC08D" },
  "Next.js": { Icon: SiNextdotjs, color: "#303841" },
  "Node.js": { Icon: FaNodeJs, color: "#339933" },
  "Express": { Icon: SiExpress, color: "#303841" },
  "Express.js": { Icon: SiExpress, color: "#303841" },
  "Flask": { Icon: SiFlask, color: "#303841" },
  "Ionic": { Icon: SiIonic, color: "#3880FF" },
  "Bootstrap": { Icon: FaBootstrap, color: "#7952B3" },
  "Tailwind CSS": { Icon: SiTailwindcss, color: "#06B6D4" },
  "Vite 6": { Icon: SiVite, color: "#646CFF" },
  "Vite": { Icon: SiVite, color: "#646CFF" },
  "FastAPI": { Icon: SiFastapi, color: "#009688" },
  "DuckDB": { Icon: SiDuckdb, color: "#FFF000" },
  "Framer Motion": { Icon: FaBolt, color: "#D72323" },
  "Spring Boot": { Icon: SiSpringboot, color: "#6DB33F" },
  "MySQL": { Icon: SiMysql, color: "#4479A1" },
  "PostgreSQL": { Icon: SiPostgresql, color: "#336791" },
  "Postgres": { Icon: SiPostgresql, color: "#336791" },
  "Supabase": { Icon: SiSupabase, color: "#3ECF8E" },
  "MongoDB": { Icon: SiMongodb, color: "#47A248" },
  "SQL": { Icon: FaDatabase, color: "#3A4750" },
  "Banco de Dados": { Icon: FaDatabase, color: "#3A4750" },
  "SQLite": { Icon: FaDatabase, color: "#3A4750" },
  "Pandas": { Icon: SiPandas, color: "#9e9e9e" },
  "NumPy": { Icon: SiNumpy, color: "#4DABCF" },
  "Jupyter": { Icon: SiJupyter, color: "#F37726" },
  "TensorFlow": { Icon: SiTensorflow, color: "#FF6F00" },
  "OpenCV": { Icon: SiOpencv, color: "#5C3EE8" },
  "MediaPipe": { Icon: FaEye, color: "#4DABCF" },
  "cvzone": { Icon: FaVideo, color: "#4DABCF" },
  "PyCaw": { Icon: FaVolumeUp, color: "#9e9e9e" },
  "psutil": { Icon: FaMemory, color: "#9e9e9e" },
  "Groq": { Icon: FaBolt, color: "#D72323" },
  "Groq SDK": { Icon: FaBolt, color: "#D72323" },
  "LLMs": { Icon: FaRobot, color: "#D72323" },
  "IA": { Icon: FaRobot, color: "#D72323" },
  "OpenAI": { Icon: FaRobot, color: "#9e9e9e" },
  "APIs": { Icon: FaPlug, color: "#9e9e9e" },
  "API REST": { Icon: FaPlug, color: "#9e9e9e" },
  "SSE": { Icon: FaBolt, color: "#9e9e9e" },
  "BeautifulSoup": { Icon: FaCode, color: "#9e9e9e" },
  "pypdf": { Icon: FaFilePdf, color: "#9e9e9e" },
  "Power BI": { Icon: FaChartBar, color: "#F2C811" },
  "DAX": { Icon: FaChartLine, color: "#F2C811" },
  "Power Query": { Icon: FaDatabase, color: "#F2C811" },
  "Excel": { Icon: FaFileExcel, color: "#217346" },
  "Microsoft Excel": { Icon: FaFileExcel, color: "#217346" },
  "Recharts": { Icon: FaChartLine, color: "#8884d8" },
  "PGLite": { Icon: FaDatabase, color: "#336791" },
  "TanStack Router": { Icon: FaLayerGroup, color: "#FF4154" },
  "Git": { Icon: FaGitAlt, color: "#F05032" },
  "GitHub": { Icon: FaGithub, color: "#303841" },
  "Docker": { Icon: FaDocker, color: "#2496ED" },
  "AWS": { Icon: FaAws, color: "#FF9900" },
  "Railway": { Icon: SiRailway, color: "#303841" },
  "Netlify": { Icon: SiNetlify, color: "#00C7B7" },
  "Linux": { Icon: FaLinux, color: "#FCC624" },
  "Vim": { Icon: SiVim, color: "#019733" },
  "POO": { Icon: FaCode, color: "#ED8B00" },
  "HTML5": { Icon: FaHtml5, color: "#E34F26" },
  "CSS3": { Icon: FaCss3Alt, color: "#1572B6" },
  "Scrum": { Icon: FaLayerGroup, color: "#9e9e9e" },
};

export function TechIcon({ name }: { name: string }) {
  const found = MAP[name];
  if (!found) return <span className="h-1.5 w-1.5 rounded-full bg-[#D72323]"></span>;
  const { Icon, color } = found;
  return <Icon size={15} style={{ color }} />;
}
